### ISSUE TITLE
PA Review: Select price & confirm

### ISSUE THREAD

**Issue by brillantewang** [brillantewang/taskwombat#5]

**Comment by brillantewang** [comment]
The only weird thing is that if you hit refresh at any point during the forms, the state gets reset so it doesn't have the task data anymore when you try to submit and create the task at the end, resulting in errors. 

I think there may be a workaround for that by using local storage. Gonna try to figure this out in the next couple hours.

**Comment by LochandQuay** [comment]
@brillantewang 
That's pretty normal for most forms, though. I don't think you should worry about that. Like, if I'm checking out of an online store, I don't want to refresh and still see my credit card information. In most cases, I feel like if I were to refresh, there's an alert that comes up that's like "Are you sure you want to leave this page? All progress will be lost" or something.
