### ISSUE TITLE
PA Review: New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by brillantewang** [brillantewang/taskwombat#7]

**Comment by brillantewang** [comment]
https://taskwombat.herokuapp.com/#/

**Comment by LochandQuay** [comment]
@brillantewang 
Quick initial comment:
- [x] Add a link to be able to toggle the form (e.g., "Already have an account? Log in"/"Don't have an account? Sign up")

**Comment by LochandQuay** [comment]
@brillantewang 

Console Errors:
- [ ] Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `preventDefault` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use `event.persist()`. See https://fb.me/react-event-pooling for more information.
- [ ] Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack

Styling Issues:
- [x] Location of errors different between forms. It's a bit jarring. Just wanted to point that out.

General Issues (will need to be fixed before Friday):
- [x] Minification Warning
- [x] Mixed Content Warning

**Comment by brillantewang** [comment]
Styling Issues:
- Made errors inline for login form so match sign up form
- Added an error modal on login form (like on taskrabbit website)

**Comment by brillantewang** [comment]
What exactly do you mean by 'Minification Warning' and 'Mixed Content Warning'? What are those?
